name: Run tests

on:
   push:
      branches: ["master"]
   pull_request:
      branches: ["master"]

jobs:
   build:
      name: Run tests
      runs-on: ubuntu-latest
      steps:
         -  run: node --version
         -  run: yarn --version
         -  name: checkout repo
            uses: actions/checkout@v3
         -  name: use node.js
            uses: actions/setup-node@v3
            with:
               node-version: '21'
         -  run: yarn install
         -  run: yarn lint
         -  run: yarn test
         -  name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v4.0.1
