name: Tests workflow

on:
   push:
      branches: ["master"]
   pull_request:
      branches: ["master"]

jobs:
   build:
      name: Run tests
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@v2

         -  uses: actions/setup-node@v1
            with:
               node-version: '21'

         -  uses: browser-actions/setup-chrome@latest
            with:
               chrome-version: stable

         -  run: npm install

         -  run: npm run lint

         -  run: npm test
